version: 0.2
phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  base-directory: .
  files: ['dist/**/*', 'package.json', 'package-lock.json']
  discard-paths: no